#!/usr/bin/bash
rm -r Logs_Java_Smells
mkdir Logs_Java_Smells

cd Repos_Java

echo Deleting curly brackets ...
find . -type f -name '*.java' -exec sh -c '
  for f do
    bash ../delete_lines_with_curly_brackets $f
  done' sh {} +

echo Deleting empty lines in .java files ...
find -type f -name '*.java' -exec sed -i '/^\s*$/d' {} + # deletes all empty lines in all java files in the subdirs

filename="../java_repository_names"
while read -r line; do
    complete_line="$line"
    rep_name="$( cut -d ',' -f 1 <<< "$complete_line" )" 
    echo +-------------------------------------------------+
    echo Checking $rep_name ...
    echo +-------------------------------------------------+
    ../pmd-bin-6.9.0/bin/run.sh pmd -d ../Repos_Java/${rep_name##*/}/ -no-cache -f xml -R ../rules.xml >> ../Logs_Java_Smells/${rep_name##*/}
done < "$filename"
