#!/usr/bin/bash
rm -r Logs_Kotlin_Smells
mkdir Logs_Kotlin_Smells

cd Repos_Kotlin

find -type f -name '*.kt' -exec sed -i '/^\s*$/d' {} + # deletes all empty lines in all java files in the subdirs

filename="../kotlin_repository_names"
while read -r line; do
    complete_line="$line"
    rep_name="$( cut -d ',' -f 1 <<< "$complete_line" )" 
    java -jar ../detekt/detekt-cli/build/libs/detekt-cli-1.0.0-RC11-all.jar --input ../Repos_Kotlin/${rep_name##*/} >> ../Logs_Kotlin_Smells/${rep_name##*/}
    #echo ${rep_name##*/} # only the part after the last slash character
done < "$filename"
