#!/bin/bash

IFS=$'\n'; set -f
counter=0
for filename in $(find $1 -name '*.java'); do

filename_with_extension=$(echo "${filename}" | sed 's:.*/::')
filename_without_extension="$( cut -d '.' -f 1 <<< "$filename_with_extension" )" 

if (( ${#filename_without_extension} > 25 )); then
	((counter++))
fi

done
unset IFS; set +f

echo $counter
