#!/usr/bin/bash
rm -r Logs_Java_Smells Logs_Kotlin_Smells
mkdir Logs_Java_Smells Logs_Kotlin_Smells

cd Repos_Java

find -type f -name '*.java' -exec sed -i '/^\s*$/d' {} + # deletes all empty lines in all java files in the subdirs

filename="../java_repository_names"
while read -r line; do
    rep_name="$line" 
    ../pmd-bin-6.9.0/bin/run.sh pmd -d ../Repos_Java/${rep_name##*/}/ -no-cache -f xml -R ../rules.xml >> ../Logs_Java_Smells/${rep_name##*/}
    #echo ${rep_name##*/} # only the part after the last slash character
done < "$filename"

cd ..
cd Repos_Kotlin
filename="../kotlin_repository_names"
while read -r line; do
    rep_name="$line" 
    java -jar ../detekt/detekt-cli/build/libs/detekt-cli-1.0.0-RC11-all.jar --input ../Repos_Kotlin/${rep_name##*/} >> ../Logs_Kotlin_Smells/${rep_name##*/}
    #echo ${rep_name##*/} # only the part after the last slash character
done < "$filename"
