#!/usr/bin/bash
rm -r Logs_Kotlin_Smells
mkdir Logs_Kotlin_Smells

cd Repos_Kotlin

echo Deleting empty lines in .kt files ...
find -type f -name '*.kt' -exec sed -i '/^\s*$/d' {} + # Deletes all empty lines in all Kotlin files in the subdirs

filename="../kotlin_repository_names"
while read -r line; do
    complete_line="$line"
    rep_name="$( cut -d ',' -f 1 <<< "$complete_line" )"
    echo +-------------------------------------------------+
    echo Checking $rep_name
    echo +-------------------------------------------------+ 
    java -jar ../detekt/detekt-cli/build/libs/detekt-cli-1.0.0-RC11-all.jar --input ../Repos_Kotlin/${rep_name##*/} >> ../Logs_Kotlin_Smells/${rep_name##*/}
done < "$filename"
