#!/bin/bash
csv_file=java_code_smells.csv
rm $csv_file
rep_names="java_repository_names"
echo Project, LC, LM, LPL, TMM >> $csv_file
while read -r line; do
	rep_name="$line"
	rep_name="Logs_Java_Smells/${rep_name##*/}"
	excessiveClassLengthSmellCount=0
	excessiveMethodLengthSmellCount=0
	excessiveParameterListSmellCount=0
	tooManyMethodsSmellCount=0
	excessiveClassLengthSmellCount=$(grep -c "ExcessiveClassLength" $rep_name)
	excessiveMethodLengthSmellCount=$(grep -c "ExcessiveMethodLength" $rep_name)
	excessiveParameterListSmellCount=$(grep -c "ExcessiveParameterList" $rep_name)
	tooManyMethodsSmellCount=$(grep -c "TooManyMethods" $rep_name)
	echo ${rep_name##*/}, $excessiveClassLengthSmellCount, $excessiveMethodLengthSmellCount, $excessiveParameterListSmellCount, $tooManyMethodsSmellCount  >> $csv_file
done < "$rep_names"  

