#!/usr/bin/bash
rm -r -f Repos_Java Repos_Kotlin
mkdir Repos_Java
cd Repos_Java
filename="../java_repository_names"
while read -r line; do
    rep_name="$line"
    git clone https://github.com/$rep_name.git
    echo "cloned $rep_name"
done < "$filename"

cd ..
mkdir Repos_Kotlin
cd Repos_Kotlin
filename="../kotlin_repository_names"
while read -r line; do
    rep_name="$line"
    git clone https://github.com/$rep_name.git
    echo "cloned $rep_name"
done < "$filename"
