#!/bin/bash
csv_file=kotlin_code_smells.csv
rm $csv_file
rep_names="kotlin_repository_names"
echo Project, LF '(t=30)', LC '(t=100)', LM'(t=20)', LPL'(t=2)', TMM'(t=5)', Total, Lifespan, Issues, LOC, Commits, Contributors, Stargazers >> $csv_file
while read -r line; do
	complete_line="$line"
	rep_name="$( cut -d ',' -f 1 <<< "$complete_line" )"

	lifespan="$( cut -d ',' -f 2 <<< "$complete_line" )"
	issues="$( cut -d ',' -f 3 <<< "$complete_line" )"
	stargazers_count="$( cut -d ',' -f 4 <<< "$complete_line" )"
	log_file="Logs_Kotlin_Smells/${rep_name##*/}"
	cd Repos_Kotlin/${rep_name##*/}	
	contributors=$(git log --all --pretty="%an" | sort | uniq | wc -l)
        commits=$(git rev-list --all --count)
	loc=$(find . -type f -name '*.kt' -exec cat {} \; | sed '/^\s*#/d;/^\s*$/d;/^\s*\/\//d' | wc -l)
	cd ..
	cd ..
	excessiveParameterListSmellCount=$(grep -c "LongParameterList" $log_file)
	tooManyMethodsSmellCount=$(grep -c "TooManyFunctions" $log_file)

	IFS=$'\n'; set -f
	filename_length_counter=0
	for filename in $(find Repos_Kotlin/${rep_name##*/} -name '*.kt'); do

	filename_with_extension=$(echo "${filename}" | sed 's:.*/::')
	filename_without_extension="$( cut -d '.' -f 1 <<< "$filename_with_extension" )" 

	if (( ${#filename_without_extension} > 30 )); then
	((filename_length_counter++))
	fi

	done
	unset IFS; set +f

	total=$(($filename_length_counter+$excessiveParameterListSmellCount+$tooManyMethodsSmellCount))
	echo $rep_name, $filename_length_counter, $excessiveParameterListSmellCount, $tooManyMethodsSmellCount, $total, $lifespan, $issues, $loc, $commits, $contributors, $stargazers_count  >> $csv_file
done < "$rep_names"    










	
	
