#!/bin/bash
csv_file=java_code_smells.csv
rm $csv_file
rep_names="java_repository_names"
echo Project, LC '(t=100)', LM'(t=20)', LPL'(t=2)', TMM'(t=5)', Total, Lifespan, Issues, LOC, Commits, Contributors, Stargazers >> $csv_file
while read -r line; do
	complete_line="$line"
	rep_name="$( cut -d ',' -f 1 <<< "$complete_line" )"
	lifespan="$( cut -d ',' -f 2 <<< "$complete_line" )"
	issues="$( cut -d ',' -f 3 <<< "$complete_line" )"
	stargazers_count="$( cut -d ',' -f 4 <<< "$complete_line" )"
	log_file="Logs_Java_Smells/${rep_name##*/}"
	cd Repos_Java/${rep_name##*/}	
	contributors=$(git log --all --pretty="%an" | sort | uniq | wc -l)
	commits=$(git rev-list --all --count)
	loc=$(find . -type f -name '*.java' -exec cat {} \; | sed '/^\s*#/d;/^\s*$/d;/^\s*\/\//d' | wc -l)
	cd ..
	cd ..
	excessiveClassLengthSmellCount=$(grep -c "ExcessiveClassLength" $log_file)
	excessiveMethodLengthSmellCount=$(grep -c "ExcessiveMethodLength" $log_file)
	excessiveParameterListSmellCount=$(grep -c "ExcessiveParameterList" $log_file)
	tooManyMethodsSmellCount=$(grep -c "TooManyMethods" $log_file)
	total=$(($excessiveClassLengthSmellCount+$excessiveMethodLengthSmellCount+$excessiveParameterListSmellCount+$tooManyMethodsSmellCount))
	echo ${rep_name##*/}, $excessiveClassLengthSmellCount, $excessiveMethodLengthSmellCount, $excessiveParameterListSmellCount, $tooManyMethodsSmellCount, $total, $lifespan, $issues, $loc, $commits, $contributors, $stargazers_count  >> $csv_file
done < "$rep_names"  
