#!/usr/bin/bash
#rm java_repository_names kotlin_repository_names
#python3 load_repository_names.py # loads repo names via github api and saves them in files
#bash load_java_repos # cloning repositories by reading the files
#bash load_kotlin_repos 
#bash check_java_smells # uses pmd to analyse the java repositories and saves the logs
#bash check_kotlin_smells # uses detekt to analyse the kotlin repositories and saves the logs
bash read_write_java_data # checks the logs and sums up the code smells
bash read_write_kotlin_data # checks the logs and sums up the code smells

