#!/usr/bin/bash

rm java_repository_names kotlin_repository_names # Removes the existing repositories names

# The following loads reposoitory names via GitHub API and saves them in files
# Use arguments to indicate the sample size you prefer: 100, 200, 300, 400, 500, 1000
# Example: #python3 load_repository_names.py 300
# When no argument is given, the default (5) sample size will be used
python3 load_repository_names.py 

# By using the following commands, Kotlin projects will be downloaded and analysed

bash load_kotlin_repos # Clones repositories by reading the files
bash check_kotlin_smells # Uses Detekt to analyse the Kotlin repositories and saves the logs
bash read_write_kotlin_data # Checks the logs and sums up the code smells

# By using the following commands Java projects will be downloaded and analysed

bash load_java_repos # Clones repositories by reading the files
bash check_java_smells # Uses PMD to analyse the Java repositories and saves the logs
bash read_write_java_data # Checks the logs and sums up the code smells
