#! /bin/bash

cd auxiliary_scripts
bash delete_all_comments ../$1
bash delete_empty_lines ../
bash save_linenumbers ../$1 $2
bash tweak_saved_linenumbers
bash add_char_to_linenumber $3
bash insert_character ../$1 $2
bash delete_lines_with_curly_brackets ../$1 $2

